
GET http://127.0.0.1:8000/get-list HTTP/1.1
Content-Type: application/json

POST http://127.0.0.1:8000/save-device HTTP/1.1
Content-Type: application/json

{
    "user_id": "d418e0c8-b636-4075-9b64-808679e3eedc",
    "cpu_name": "AMD Ryzen 7 5700G",
    "ram_storage": "24 GB",
    "ip_address": "10.0.2.5",
    "storage": "100GB"
}

GET http://127.0.0.1:8000/get-users HTTP/1.1
Content-Type: application/json

POST http://127.0.0.1:8000/save-user HTTP/1.1
Content-Type: application/json

{
    "fullname": "Diego Benaglio",
    "area": "Analyst",
    "username": "dbenaglio",
    "password": "1q2w3e4r"
}

#{
#    "username": "msolisci",
#    "password": "1z2x3c4v"
#}

